services:
  caddy:
    image: caddy:2-alpine
    container_name: sepericosahedron-dev
    restart: unless-stopped
    ports:
      - "8282:8282"
    volumes:
      - ./caddy_data:/data:rw
      - ./caddy_config:/config:rw
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./build:/srv/build:ro
      - ./template.html:/srv/template.html:ro
      - frontend-dist-volume:/srv/dist:ro

  frontend:
    image: ghcr.io/akorzunin/supericosahedron-frontend:latest
    container_name: sepericosahedron-frontend-dev
    volumes:
      - frontend-dist-volume:/src/web/dist
    command: ["tail", "-F", "aboba"]

volumes:
  frontend-dist-volume:
