services:
  caddy:
    image: ghcr.io/akorzunin/supericosahedron-frontend:latest
    container_name: supericosahedron-dev
    restart: unless-stopped
    ports:
      - "8282:8282"
    volumes:
      - ./caddy_data:/data:rw
      - ./caddy_config:/config:rw
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./build:/srv/build:ro
